name: pharmacyapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cloud_firestore: ^6.1.1
  curved_navigation_bar: ^1.0.6
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  http: ^1.6.0
  random_string: ^2.3.1
  shared_preferences: ^2.5.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
  - images\boy_image.jpeg
  - images\medicine_image.png
  - images\wallet.png
  - images\cashback.png
  - images\debite.png
  - images\splash.jpg
  - images\Farmacia.png


